apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "backstage-tutorial"
  description: "tuto"
  annotations:
    github.com/project-slug: ren4nh/backstage-tuto
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
